# Aplicaciones

bind = $mainMod, Q, exec, $terminal
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, B, exec, $navegator
bind = $mainMod, R, exec, flatpak run io.missioncenter.MissionCenter
bind = $mainMod, O, exec, waypaper
