$screenshots = /home/rojuma/Imágenes/Capturas\ de\ pantalla/

# Capturas

bind = $mainMod, PRINT, exec, hyprshot -m window -o $screenshots

bind = SHIFT, PRINT, exec, hyprshot -m output -o $screenshots

bind = , PRINT, exec, hyprshot -m region -o $screenshots
