background {
    monitor = eDP-1
    color = rgba(25, 20, 20, 1.0)
    path = ~/Imágenes/wallpapers/ghoul/12.jpg
    blur_passes = 2
    blur_size = 4
}

input-field {
    monitor = eDP-1

    size = 320, 55

    position = 0, -90

    halign = center
    valign = center

    dots_center = true
    fade_on_empty = false

    rounding = 15

    outer_color = rgb(5E81AC)
    inner_color = rgba(20,20,20,0.85)

    font_color = rgb(FFFFFF)

    placeholder_text = Contraseña
}

label {
    monitor = eDP-1
    text = $TIME
    font_size = 90
    position = 0, 180
    halign = center
    valign = center
}

label {
    monitor = eDP-1
    text = cmd[update:1000] date +"%A, %d %B %Y"

    font_size = 24

    position = 0, 110

    halign = center
    valign = center
}

label {
    monitor = eDP-1
    text = Rojuma

    font_size = 28

    position = 0, 40

    halign = center
    valign = center
}

label {
    monitor = eDP-1
    text = cmd[update:30000] upower -i $(upower -e | grep BAT) | grep percentage | awk '{print $2}'

    font_size = 18

    position = 0, -180

    halign = center
    valign = center
}
