#################
### AUTOSTART ##
#################

exec-once = waybar
exec-once = awww-daemon
#exec-once = hyprlauncher -d
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = nm-applet
#exec-once = swaync
exec-once = blueman-applet
exec-once = hypridle
exec-once = killall xdg-desktop-portal; killall xdg-desktop-portal-hyprland; /usr/lib/xdg-desktop-portal &
exec-once = ~/.local/bin/battery-alert.sh
exec-once = swww init
exec-once = ~/.local/bin/wallpaper-wallust.sh
