#############################
### ENVIRONMENT VARIABLES ##
#############################

env = XDG_CURRENT_DESKTOP,Hyprland

env = HYPRCURSOR_THEME,Future-Cyan-Hyprcursor_Theme

env = XCURSOR_SIZE,26

env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
