source = ~/.config/hypr/keybinds/apps.conf
source = ~/.config/hypr/keybinds/windows.conf
source = ~/.config/hypr/keybinds/workspaces.conf
source = ~/.config/hypr/keybinds/mouse.conf
source = ~/.config/hypr/keybinds/screenshots.conf
source = ~/.config/hypr/keybinds/multimedia.conf
source = ~/.config/hypr/keybinds/launcher.conf
source = ~/.config/hypr/keybinds/bloque.conf
