###################
### PROGRAMS ######
###################

$terminal = kitty
$fileManager = thunar
$menu = rofi -show drun
$navegator = zen-browser

###################
### MOD KEY #######
###################

$mainMod = SUPER
